### ISSUE TITLE
Name confusion

### ISSUE THREAD

**Issue by lassik** [kbenzie/git-cmake-format#16]
There now exists a program called `cmake-format` for auto-formatting CMake listfiles (written in Python: `pip install cmake-format` and then run `cmake-format` from the command line). The name of `git-cmake-format` is a bit confusing under the circumstances since AFAICT it doesn't use `cmake-format` :)

**Comment by kbenzie** [comment]
Sorry for your confusion but I don't see how this affects me.

First of all the [README](https://github.com/kbenzie/git-cmake-format/blob/master/readme.md) clearly states the purpose of this project.

Secondly, the first commit of this project is dated [27 Aug 2014](https://github.com/kbenzie/git-cmake-format/commit/8f3da39cab7ca90f40fc095ff6584d112530d0f3) and the first commit of the project you mention is [12 May 2016](https://github.com/cheshirekow/cmake_format/commit/a8a8146a5cf4d383865f5753767052acb01f2e5b).

Thirdly, GitHub is full of similarly named projects which do different things, this is not a python package hosted on [PyPi](https://pypi.org/).

I'm going to close this issue as this as it does not make a suggestion and it's purpose seems to only be inform me of your confusion. If you're looking for a tool similar to [git-clang-format](https://github.com/llvm-mirror/clang/blob/master/tools/clang-format/git-clang-format) for `cmake-format` I don't think it exists but there's nothing stopping someone, perhaps yourself, from creating it with the same project name as this one.

**Comment by lassik** [comment]
Thanks for the thoughtful response. I understand your decision, especially as your project came first. I opened this issue in case you hadn't heard of cmake-format and wanted to consider explicitly mentioning "clang-format" in the name of your project for clarity. I should have been clearer in my initial post.
