### ISSUE TITLE
Exclude some files?

### ISSUE THREAD

**Issue by jbreitbart** [kbenzie/git-cmake-format#5]
Is it possible to exclude some files from the format checking / reformating? I typically use a vendor directory, which includes sources coming from 3rd parties, which should stay the way I received them.

What is the best way to implement such a feature? Do you have an idea?

**Comment by kbenzie** [comment]
Sorry for the late response, I wasn't getting email updates. They have been enabled again.

So this is a feature that I had considered, up until now I've been doing this manually when committing files I don't want formatted by disabling verification.

```
git commit --no-verify
```

However this is error prone. From you're description its sounds like you want to disable directories as opposed to individual files which should make life easier.

The approach I will likely take is to add a CMake variable, such as `GCF_IGNORE_LIST`, containing a list of directories and pass it to the python script to check if changed files are in the list of ignored directories.

**Comment by kbenzie** [comment]
So as per my previous comment I've added the `GCF_IGNORE_LIST` CMake variable which takes a semi colon separated list of directory paths and passes these onto the python script.

See 96e102e1bb4b1f1c075816e09013691bffae4ce7 and 4fd1389a6dfdb76718c23d84402d9fea7672a4dc for the relevant changes.

**Comment by jbreitbart** [comment]
Great, thanks!
